language: generic
env:
- MORE_WARNINGS=1
- NO_SSE=1

matrix:
  include:
    - os: linux
      sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libreadline-dev

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons sdl2; fi
  - scons -Q -j1 debug=0 force32=0 no_sql=1 project=game,cgame,ui tools=default CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5
